### ISSUE TITLE
Remove empty RDF

### ISSUE THREAD

**Issue by imartinezortiz** [e-ucm/xapi-profile2html#2]
/CC @jhaag75: you want to remove that `<td rel="skos:closeMatch" resource="">`

**Comment by jhaag75** [comment]
On last suggestion: Can you specify what type of extension (e.g. result,
context, etc) is being used in the description for your extensions. We had
thought about conveying this in the IRI itself, but decided that was a bad
idea. But it would still be helpful to others using your profile to know
what type of extension it is, perhaps.

---

+1.850.266.7100(office)
+1.850.471.1300 (mobile)
jhaag75 (skype)
http://jasonhaag.com (Web)
http://twitter.com/mobilejson (Twitter)
http://linkedin.com/in/jasonhaag (LinkedIn)

**Comment by anserran** [comment]
Updated in https://github.com/e-ucm/xapi-seriousgames/commit/6c3e0239aa88cbcef32820f535db9c63d2fd501e
